export const CRYPTOCURRENCY_GET_REQUEST = 'CRYPTOCURRENCY_GET_REQUEST'
export const CRYPTOCURRENCY_GET_SUCCESS = 'CRYPTOCURRENCY_GET_SUCCESS'
export const CRYPTOCURRENCY_GET_FAILURE = 'CRYPTOCURRENCY_GET_FAILURE'
