export const REGISTRATION_GET_REQUEST = 'REGISTRATION_GET_REQUEST'
export const REGISTRATION_GET_SUCCESS = 'REGISTRATION_GET_SUCCESS'
export const REGISTRATION_GET_FAILURE = 'REGISTRATION_GET_FAILURE'
export const REGISTRATION_GET_CLEAR = 'REGISTRATION_GET_CLEAR'
